export const JOBS_DATA = [
  {
    id: 1,
    title: "IT Support Intern",
    company: "United Global Services Company",
    location: "Dubai, AE",
    datePosted: "2025-03-01",
    category: "IT Support",
    featured: true,
    imageUrl: "/images/Job.jpg",
    description: "You will join a cross-functional IT operations team handling first and second line support across desktops, mobile devices, conferencing equipment, and core productivity services. This internship exposes you to structured ticket triage, escalation paths, and root cause analysis in a live business environment.\n\nDaily activities include diagnosing workstation performance issues, assisting with account provisioning / deprovisioning, documenting recurring fixes to expand the self‑service knowledge base, and participating in preventative maintenance (patch cycles, inventory audits, backup checks). You'll collaborate with cybersecurity on endpoint hardening and learn how governance policies (password rotation, least privilege) are enforced in practice.\n\nBy the end of the internship you will understand how metrics (MTTR, ticket deflection, SLA adherence) drive process improvement and how automation scripts reduce repetitive effort across the fleet.",
    requirements: [
      "Currently pursuing a degree in Computer Science, IT, or related field",
      "Fundamental knowledge of Windows and macOS user environments",
      "Ability to install and configure common productivity software",
      "Basic understanding of TCP/IP, DNS, DHCP concepts",
      "Familiarity with scripting (PowerShell or Bash) – simple loops/conditions",
      "Strong customer empathy and clear written communication",
      "Organized approach to documenting steps and resolutions",
      "Willingness to learn ITIL-style incident categorization and priorities",
      "Bonus: Exposure to MDM tools (Intune, Jamf) or ticketing (Jira, Zendesk)",
    ],
    skills: ["Troubleshooting", "Windows", "macOS", "Microsoft 365", "Networking Basics"],
    degree: "BSc (In Progress) Computer Science / IT",
    qualifications: "CompTIA A+ (nice to have)",
    experience: "0 - 1 year",
    visaOptions: ["Student Visa", "Parent Visa", "Emirati Visa"],
  },
  {
    id: 2,
    title: "Frontend Developer Intern",
    company: "Tech Solutions Inc.",
    location: "New York, US",
    datePosted: "2025-02-28",
    category: "Frontend",
    featured: false,
    imageUrl: "/images/Job.jpg",
    description: "Collaborate with product designers and backend engineers to deliver accessible, performant user interfaces. You will help implement atomic UI components, responsive layout systems, and data visualization elements using modern tooling (TypeScript, Next.js, TailwindCSS).\n\nYou will participate in code reviews focused on stability, bundle size, and accessibility (WCAG compliance). Expect to instrument components with basic analytics events, experiment flags, and loading skeletons to optimize user perception.\n\nYou will gain experience profiling rendering bottlenecks (React DevTools, Lighthouse) and mitigating them with memoization, lazy loading, and progressive hydration strategies.",
    requirements: [
      "Solid grasp of semantic HTML and modern CSS layout (Flexbox, Grid)",
      "Comfortable with JavaScript ES2015+ and basic TypeScript types",
      "Introductory experience with React or Next.js (hooks, routing)",
      "Ability to consume REST or simple GraphQL endpoints",
      "Understanding of component composition and props drilling vs context",
      "Basic git workflow (branching, pull requests, rebasing)",
      "Attention to accessibility (aria attributes, focus states)",
      "Eagerness to write small unit tests (Jest, Testing Library)",
      "Bonus: Familiarity with performance metrics (TTI, CLS, LCP)",
    ],
    skills: ["React", "Next.js", "TailwindCSS", "TypeScript", "Git"],
    degree: "BSc Computer Science / Software Engineering",
    qualifications: "Portfolio or GitHub projects",
    experience: "0 - 1 year",
    visaOptions: ["Student Visa", "Intern Visa"],
  },
  {
    id: 3,
    title: "DevOps Engineer Intern",
    company: "Cloud Innovators",
    location: "Berlin, DE",
    datePosted: "2025-03-03",
    category: "DevOps",
    featured: true,
    imageUrl: "/images/Job.jpg",
    description: "Work alongside senior platform engineers to streamline build, test, and deployment workflows. You will help maintain infrastructure-as-code templates (Terraform), refine CI/CD pipelines (GitHub Actions) for parallelized test stages, and contribute to container image optimization (multi-stage builds, caching).\n\nMonitoring exposure includes setting alert thresholds, tuning noisy metrics, and tracing request paths through distributed services (OpenTelemetry basics). Security-adjacent tasks may involve scanning dependencies (SCA), reviewing container vulnerability reports, and applying least-privilege IAM policies.\n\nYou will learn how feedback loops—observability dashboards feeding into deployment strategies (blue/green, canary)—improve reliability and rollback confidence.",
    requirements: [
      "Comfort using Linux shell (navigation, permissions, processes)",
      "Foundational understanding of CI/CD lifecycle stages",
      "Introductory Docker knowledge (layers, images, containers)",
      "Basic scripting (Bash or Python) for automation",
      "Awareness of cloud service models (IaaS, PaaS) and core AWS/GCP services",
      "Understanding of version control branching strategies",
      "Eager to learn infrastructure-as-code (Terraform or CloudFormation)",
      "Bonus: Familiarity with monitoring stacks (Prometheus, Grafana)",
      "Bonus: Awareness of security scanning tools (Trivy, Snyk)",
    ],
    skills: ["Linux", "Docker", "CI/CD", "Bash", "Monitoring"],
    degree: "BSc Computer Science / DevOps Track",
    qualifications: "Any cloud fundamentals cert (plus)",
    experience: "0 - 1 year",
    visaOptions: ["EU Student", "Intern Visa"],
  },
  {
    id: 4,
    title: "Backend Developer Intern",
    company: "Creative Studio",
    location: "San Francisco, US",
    datePosted: "2025-03-02",
    category: "Backend",
    featured: false,
    imageUrl: "/images/Job.jpg",
    description: "Contribute to service-layer logic powering customer-facing features. You will implement RESTful or lightweight GraphQL endpoints, enforce validation / sanitization, and write integration tests around persistence layers. Expect exposure to pagination strategies, error modeling, and transactional integrity.\n\nPerformance tasks may include identifying N+1 query patterns, adding selective indexes, and instrumenting latency metrics. You'll collaborate with frontend peers to refine API contracts and experiment with idempotent mutation handling.\n\nYou will also assist in refactoring monolithic modules into domain-aligned slices preparing for future microservice boundaries.",
    requirements: [
      "Fundamental knowledge of Node.js (async/await, modules)",
      "Understanding of HTTP methods, status codes, and REST patterns",
      "Ability to write basic SQL (SELECT, JOIN, WHERE)",
      "Familiarity with an ORM (Prisma, Sequelize, TypeORM) or query builder",
      "Basic error handling and logging principles",
      "Git-based collaboration (PR reviews, resolving merge conflicts)",
      "Unit + integration test exposure (Jest, supertest)",
      "Understanding of environment variable configuration",
      "Bonus: Exposure to message queues (RabbitMQ, Kafka)",
    ],
    skills: ["Node.js", "Express", "PostgreSQL", "REST", "Git"],
    degree: "BSc Computer Science / Software Engineering",
    qualifications: "Open-source or project work",
    experience: "0 - 1 year",
    visaOptions: ["Student Visa", "Intern Permit"],
  },
  {
    id: 5,
    title: "Data Analyst Intern",
    company: "Finance Corp",
    location: "London, UK",
    datePosted: "2025-02-20",
    category: "Data",
    featured: false,
    imageUrl: "/images/Job.jpg",
    description: "Support the analytics lifecycle from raw data ingestion validation to insight presentation. You'll clean and normalize disparate data sources, design concise metrics definitions (KPIs vs vanity metrics), and prototype dashboards for finance and operations stakeholders.\n\nYou will help build reproducible analysis notebooks, apply exploratory data analysis techniques (distribution profiling, outlier detection), and surface anomalies for follow‑up. Expect to translate ambiguous business questions into measurable queries and iterate quickly on visualization clarity (chart choice, labeling, color encoding).\n\nYou'll gain appreciation for data governance basics: lineage awareness, access controls, and refresh cadence monitoring.",
    requirements: [
      "Ability to write moderately complex SQL (aggregations, window functions basics)",
      "Comfort manipulating data frames in Python (pandas) or R",
      "Spreadsheet proficiency (lookup functions, pivot tables)",
      "Foundational statistics (mean, variance, correlation, distributions)",
      "Data visualization literacy (choosing appropriate chart types)",
      "Clear communication translating data into recommendations",
      "Versioning analysis artifacts (Git)",
      "Bonus: Exposure to BI tools (Tableau, Power BI, Metabase)",
    ],
    skills: ["SQL", "Python", "Pandas", "Data Visualization", "Dashboards"],
    degree: "BSc Data Science / Analytics",
    qualifications: "Any analytics bootcamp (plus)",
    experience: "0 - 1 year",
    visaOptions: ["Graduate Visa", "Student Visa"],
  },
  {
    id: 6,
    title: "Security Operations Intern",
    company: "Global Ventures",
    location: "Singapore, SG",
    datePosted: "2025-02-15",
    category: "Cybersecurity",
    featured: false,
    imageUrl: "/images/Job.jpg",
    description: "Participate in daily security operations: reviewing SIEM alerts, correlating suspicious activity across logs, and assisting in incident response documentation. You'll help tune detection rules to reduce false positives, compile short threat briefs, and maintain an inventory of prioritized vulnerabilities with remediation follow‑ups.\n\nYou will observe how escalation paths function between SOC tiers and how containment vs eradication decisions are made under time pressure. Expect structured exposure to the NIST incident handling lifecycle (Preparation, Identification, Containment, Eradication, Recovery, Lessons Learned).\n\nYou will also aid in strengthening secure baselines: hardening checklists, patch cadence tracking, and simple script automations for repetitive log parsing.",
    requirements: [
      "Basic networking knowledge (ports, protocols, OSI layers)",
      "Familiarity with log formats (HTTP, auth, system events)",
      "Introductory understanding of common attack vectors (phishing, brute force)",
      "Interest in vulnerability scoring (CVSS basics)",
      "Clear, concise incident note‑taking and report writing",
      "Ethical mindset and respect for confidentiality",
      "Bonus: Exposure to SIEM platforms or packet analysis tools",
      "Bonus: Scripting for log filtering (Python or Bash)",
    ],
    skills: ["Networking", "SIEM", "Log Analysis", "Threat Intelligence", "Documentation"],
    degree: "BSc Cybersecurity / Information Security",
    qualifications: "Security+ (plus)",
    experience: "0 - 1 year",
    visaOptions: ["Intern Pass", "Student Visa"],
  },
  {
    id: 7,
    title: "Mobile App Developer Intern",
    company: "AppNova Labs",
    location: "Toronto, CA",
    datePosted: "2025-03-05",
    category: "Mobile",
    featured: true,
    imageUrl: "/images/Job.jpg",
  description: `Assist in building cross-platform mobile features using React Native and modern native modules. You'll help optimize rendering performance, integrate device capabilities (camera, biometrics), and refine over-the-air update strategy.

Expect to contribute to release pipelines, implement analytics event tracking, and assist with accessibility audits for inclusive design.`,
    requirements: [
      "Basic JavaScript/TypeScript fundamentals",
      "Intro React or React Native component model understanding",
      "Familiarity with mobile navigation paradigms (stack, tab)",
      "Awareness of performance considerations (bridge cost, batching)",
      "Git workflow and code review etiquette",
      "Bonus: Native Android (Kotlin) or iOS (Swift) exposure",
      "Bonus: Experience with push notifications or deep linking",
    ],
    skills: ["React Native", "TypeScript", "Mobile UI", "State Management", "Performance"],
    degree: "BSc Software Engineering / Mobile Track",
    qualifications: "Sample mobile project or GitHub repo",
    experience: "0 - 1 year",
    visaOptions: ["Coop Permit", "Student Visa"],
  },
  {
    id: 8,
    title: "Machine Learning Intern",
    company: "Insight AI Systems",
    location: "Austin, US",
    datePosted: "2025-03-06",
    category: "Machine Learning",
    featured: false,
    imageUrl: "/images/Job.jpg",
  description: `Support data scientists in prototyping and evaluating ML models for classification and anomaly detection. You will clean feature sets, run experiment tracking, and compare baselines versus incremental improvements.

You will help containerize model inference services and profile latency / memory usage under realistic loads.`,
    requirements: [
      "Python proficiency (data structures, functions)",
      "Foundational statistics & probability understanding",
      "Pandas & NumPy data manipulation basics",
      "Experience training simple models (scikit-learn)",
      "Version control of notebooks / scripts",
      "Bonus: Exposure to PyTorch or TensorFlow",
      "Bonus: Familiarity with experiment tracking (MLflow, Weights & Biases)",
    ],
    skills: ["Python", "Pandas", "scikit-learn", "Model Evaluation", "Data Cleaning"],
    degree: "BSc Data Science / AI",
    qualifications: "Kaggle or coursework projects",
    experience: "0 - 1 year",
    visaOptions: ["Intern Visa", "Graduate Visa"],
  },
  {
    id: 9,
    title: "QA Automation Intern",
    company: "QualityMatrix",
    location: "Remote",
    datePosted: "2025-03-07",
    category: "QA",
    featured: false,
    imageUrl: "/images/Job.jpg",
  description: `Help design and extend automated test suites across web and API layers. You will author stable selectors, implement smoke vs regression groupings, and analyze flaky test behavior.

You'll participate in shift-left practices—adding tests in pull requests and improving coverage metrics while keeping execution time efficient.`,
    requirements: [
      "Understanding of basic testing principles (arrange-act-assert)",
      "Familiarity with JavaScript or TypeScript",
      "Exposure to a test framework (Jest, Playwright, Cypress)",
      "Ability to read API specs (REST/JSON)",
      "Clear defect reproduction and reporting skills",
      "Bonus: CI pipeline exposure for automated test runs",
      "Bonus: Experience with visual regression or performance testing",
    ],
    skills: ["Automation", "Playwright", "Jest", "API Testing", "Debugging"],
    degree: "BSc Computer Science / Software QA",
    qualifications: "ISTQB Foundation (plus)",
    experience: "0 - 1 year",
    visaOptions: ["Remote Eligible"],
  },
];